---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# dml.sensemakr

<!-- badges: start -->
<!-- badges: end -->


## Development version

To install the development version on GitHub make sure you have the package devtools installed.

```{r, eval = FALSE}
# install.packages("devtools") 
devtools::install_github("carloscinelli/dml.sensemakr")
```



## Example

### Data
```{r example}
# loads package
library(dml.sensemakr)

## loads data
data("pension")
y <- pension$net_tfa  # net total financial assets
d <-  pension$e401    # 401K eligibility
x <- model.matrix(~ -1 + age + inc  + educ+ fsize + marr + twoearn + pira + hown, data = pension)

## compute income quartiles
g1 <- cut(x[,"inc"], quantile(x[,"inc"], c(0, 0.25,.5,.75,1), na.rm = TRUE), 
          labels = c("q1", "q2", "q3", "q4"), include.lowest = T)
```

### Fit DML
```{r}
# run DML (nonparametric model)
dml.401k <- dml(y, d, x, model = "npm", groups = g1, cf.folds = 5, cf.reps = 5)
```

### Explore results
```{r}
# summary of results with median method (default)
summary(dml.401k)

# summary of results with mean method
summary(dml.401k, combine.method = "mean")
```

### extract coefs, se, confidence intervals
```{r}
# coef median method (default)
coef(dml.401k)

# coef mean method (default)
coef(dml.401k, combine.method = "mean")

# se median method (default)
se(dml.401k); 

# se median method (default)
se(dml.401k, combine.method = "mean")

# confint median method (default)
confint(dml.401k) 

# confint mean method
confint(dml.401k, combine.method = "mean")
```



### plot

```{r}
plot(dml.401k)
```

### You can add groups after the model is fit

```{r}
## compute GATE by married
g2 <- ifelse(pension$marr, "married", "not.married")
dml.401k.g2 <- dml_gate(dml.fit = dml.401k, groups = g2)
summary(dml.401k.g2)

coef(dml.401k.g2)
confint(dml.401k.g2)
plot(dml.401k.g2)
```

## Sensitivity Analysis

### Robustness Values

```{r}
robustness_value(dml.401k, alpha = 0.05)
```
### Confidence Bounds

```{r}
confidence_bounds(dml.401k, r2ya.dx = 0.03, r2.rr = 0.04, level = 0.95)
```

### Contour Plots

```{r}
ovb_contour_plot(dml.401k, r2ya.dx = 0.03, r2.rr = 0.04, level = 0.95)
```


### Further results

```{r}
bounds.401k <- dml_bounds(dml.401k, r2ya.dx = 0.03, r2.rr = 0.04)
bounds.401k
```

```{r}
coef(bounds.401k)
se(bounds.401k)
confint(bounds.401k)
```

