---
title: "Sensitivity 401k"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{dml-401k}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  cache = T,
  comment = "#>",
  fig.align='center', collapse=T, 
  dpi=300,
  fig.width = 12, 
  fig.height = 6
)
```

```{r setup, include = FALSE}
library(dml.sensemakr)
library(ggplot2)
```

Here we reproduce the empirical example of  [Chernozhukov, V., Cinelli, C., Newey, W., Sharma A., and Syrgkanis, V. (2021). "Long Story Short: Omitted Variable Bias in Causal Machine Learning."](https://www.nber.org/papers/w30302) 

# Load Data

```{r}
# loads package
library(dml.sensemakr)

## loads data
data("pension")
y <- pension$net_tfa # net total financial assets
d <- pension$e401 # 401K eligibility
x <- model.matrix(~ -1 + age + inc + educ+ fsize + marr + twoearn + pira + hown, data = pension)
```

# Naive Estimate (no adjustment)

```{r}
mean(y[d==1]) - mean(y[d==0])
```


# Partially Linear Model

```{r}
# run DML
dml.401k.plm <- dml(y, d, x, model = "plm", cf.folds = 5, cf.reps = 5)
```



```{r}
# results under conditional ignorability
summary(dml.401k.plm)
```

```{r}
# robustness values
robustness_value(dml.401k.plm, alpha = 1) # RV point estimate
robustness_value(dml.401k.plm, alpha = 0.05) # RV confidence bound
```

```{r}
# confidence bounds under posited scenario
confidence_bounds(dml.401k.plm, cf.y = 0.04, cf.d = 0.03, level = 0.95)
```


```{r, fig.width=12}
# sensitivity contour plots
par(mfrow = c(1,2))
ovb_contour_plot(dml.401k.plm, which.bound = "lwr", cf.y = 0.04, cf.d = 0.03, 
                 bound.label = "Max match (3 years)", col.contour = "blue")
ovb_contour_plot(dml.401k.plm, which.bound = "upr", cf.y = 0.04, cf.d = 0.03, 
                 bound.label = "Max match (3 years)", col.contour = "blue")
```


```{r}
# benchmarks
bench.plm <- dml_benchmark(dml.401k.plm, benchmark_covariates = c("inc", "pira", "twoearn"))
bench.plm
```


# Nonparametric Model

```{r}
## compute income quartiles
g1 <- cut(x[,"inc"], quantile(x[,"inc"], c(0, 0.25,.5,.75,1), na.rm = TRUE), 
          labels = c("q1", "q2", "q3", "q4"), include.lowest = T)

## Nonparametric model
dml.401k.npm <- dml(y, d, x, groups = g1, model = "npm", cf.folds = 5, cf.reps = 5)
```



```{r}
# results under conditional ignorability
summary(dml.401k.npm)
```

```{r, fig.width=8}
# load ggplot2
library(ggplot2)

# coefficient plot under conditional ignorability
group.names <- paste0("gate.q",1:4)
df   <- data.frame(groups = 1:4, estimate = coef(dml.401k.npm)[group.names])
cis  <- confint(dml.401k.npm)[group.names, ]
cis  <- setNames(as.data.frame(cis), c("lwr.ci", "upr.ci"))
df   <- cbind(df, cis)
ggplot(df, aes(x = groups, y = estimate)) + geom_line() +
  geom_ribbon(aes(ymin = lwr.ci, ymax = upr.ci), alpha = 0.1, col = "blue", fill = "blue") +
  theme_bw() + 
  xlab("Income Groups by Quartiles") + 
  ylab("ATE")
```


```{r}
# robustness values
robustness_value(dml.401k.npm, alpha = 1) # RV point estimate
robustness_value(dml.401k.npm, alpha = 0.05) # RV confidence bound
```

```{r}
# bounds and confidence bounds 
bds   <- confidence_bounds(dml.401k.npm, cf.y = 0.04, cf.d = 0.03, level = 0)
bds   <- setNames(as.data.frame(bds), c("lwr.bound", "upr.bound"))
cbds  <- confidence_bounds(dml.401k.npm, cf.y = 0.04, cf.d = 0.03, level = .95)
cbds  <- setNames(as.data.frame(cbds), c("lwr.cbound", "upr.cbound"))
cbind(bds, cbds)
```

```{r, fig.width=8}
# confidence bounds plot
df2   <- cbind(df, bds[group.names,], cbds[group.names, ])
ggplot(df2, aes(x = groups, y = estimate)) + geom_line() +
  geom_ribbon(aes(ymin = lwr.bound, ymax = upr.bound),   alpha = 0.1, col = "red", fill = "red") +
  geom_ribbon(aes(ymin = lwr.cbound, ymax = upr.cbound), alpha = 0.1, col = "blue", fill = "blue") +
  theme_bw() + 
  xlab("Income Groups by Quartiles") + 
  ylab("ATE")
```

```{r, fig.width=12}
# sensitivity contour plots
par(mfrow = c(1,2))
ovb_contour_plot(dml.401k.npm, which.bound = "lwr", cf.y = 0.04, cf.d = 0.03, 
                 bound.label = "Max match (3 years)", col.contour = "blue")
ovb_contour_plot(dml.401k.npm, which.bound = "upr", cf.y = 0.04, cf.d = 0.03, 
                 bound.label = "Max match (3 years)", col.contour = "blue")
```

```{r}
# benchmarks
bench.npm <- dml_benchmark(dml.401k.npm, benchmark_covariates = c("inc", "pira", "twoearn"))
bench.npm
```

